// path: home/slider-filter-search
export const MainTitle = "Reality Properties solve your problems";
export const LatestForSale = "Latest & Featured LOT'S for sales";
export const Latestprp = "Latest & Featured property for sales";
export const SubmitProperty = "submit property";
export const KnowMore = "Know More";
export const WantToBuyOrRentHome = "Want to buy or rent Home ?";
export const Sale = "Sale";
export const FeaturedProperty = "Premium Property";
export const Featured = "Featured";
export const Rent = "Rent";
export const OurNewOffer = "Our New Offer";
export const NewOffer = "New Offer";
export const City = "City";
export const FindPropertiesInTheseCities = "Find Properties in These Cities";
export const BuyOrSell = "Buy or Sell";
export const SheltosRealEstate = "GRG Global Group real estate";
export const BannerDetail = "Looking to Buy a new property or Sell an existing one? Real Homes provides an easy solution!";
export const BrowseProperty = "Browse property";
export const MeetOurAgent = "Meet Our Team";
export const Agent = "Heads";
export const ViewPortfolio = "View Portfolio";

export const Contact = "Contact ";

export const Connect = "Connect";
export const HappyClients = "Happy clients";
export const Our = "Our";
export const LatestPropertyDetail = "GRG Provide you with a wide range of real estate services";
export const LatestPropertyDetaill = "Meet our exceptional team, ready to guide you in discovering your ideal properties.";
export const PropertyServices = "Property Types";
export const PropertyServicesDetail = "Discover a wide array of properties available in GRG!, from residential spaces to commercial ventures."
export const AreYouWorried = "Are you worried";
export const SlickAboutMovingOut = "sick about moving out?";
export const VideoDetail =
  "We know how it feels! Elegant retreat in a quiet Coral Gables setting. This home provides wonderful entertaining spaces with a chef kitchen opening Elegant retreat in a quiet Coral Gables setting.";
export const SearchNow = "Search now";
export const StayUpToDate = "Stay Up to Date";
export const OurHappyClient = "Our Happy Client";
export const Discover = "Discover New York’s best things to do, restaurants, theatre, nightlife and more";
export const PropertyOfTheDay = "Property of the day";
export const FeaturedCities = "Featured Cities";
export const proCity = "See why ProCity is one of the best friends for exploring the city.";
export const freeDownload = "free Download";
export const homeSearch = "Take your home search everywhere You go....";
export const searchAnyTime =
  "Search anytime, anywhere with ZipRealty's award-winning real estate app for iPhone, iPad and Android. See what's for sale around you and instantly request to tour homes you like.";
export const WhatPeopleSay = "Customer Testimonials";
export const docuts = "Discover the Experiences of Our Delighted Clients, Hear What They Have to Share About Their Journey with Us";
export const CEOofDesees = "CEO of Desees";
export const LatestBlog = "Latest Blog";
export const localRealEstate = "You're local Real estate";
export const classified = "Residences can be classified by and connected to residences. Different types of housing can be use same physical type.";
export const aboutMoving = "Sick about moving out?";
export const property = "Latest Property Listing";
export const propertyListing = "Property <span>Listing</span>";
export const pricingPlan = "pricing <span>Plan</span>";
export const providerServices = "Services <span>We Provide</span>";
export const propertyDescription = "Residences can be classified into different types of housing tenure can used for same physical type.";
export const Realestate = "Realestate";
export const WhatAreYouLookingFor = "What Are You Looking For";
